x-app: &default-app
  networks:
    - <project-name>-network

services:
  nginx:
    <<: *default-app
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - php
    links:
      - db
      - php

  db:
    <<: *default-app
    image: mariadb:10.2
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql

  php:
    <<: *default-app
    image: norte/magento-base
    ports:
     - "9000:9000"
    volumes:
      - ./src:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini

  redis:
    <<: *default-app
    image: redis
    ports:
     - 6379

  redis-session:
    <<: *default-app
    image: redis
    ports:
     - 6379

  elasticsearch:
    <<: *default-app
    image: elasticsearch:6.5.4
    environment:
      - node.name=magento2
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

networks:
  <project-name>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
